[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
MONGODB_URI = "mongodb+srv://admin-Jackson:@cluster0.bnu3c.mongodb.net/device-tracker?retryWrites=true&w=majority"
NODE_ENV = "production"
PORT = "8081"